/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : LeadId,
  'status' : LeadStatus,
  'name' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export interface LeadCreate {
  'status' : LeadStatus,
  'name' : string,
  'tags' : Array<string>,
  'email' : string,
  'notes' : string,
  'phone' : string,
}
export type LeadId = bigint;
export type LeadStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'contacted' : null } |
  { 'qualified' : null };
export interface MessageTemplate {
  'id' : TemplateId,
  'title' : string,
  'body' : string,
  'createdAt' : bigint,
  'attachmentUrls' : Array<string>,
}
export interface MessageTemplateCreate {
  'title' : string,
  'body' : string,
  'attachmentUrls' : Array<string>,
}
export interface SentMessage {
  'id' : SentMessageId,
  'leadIds' : Array<LeadId>,
  'subject' : string,
  'templateId' : [] | [TemplateId],
  'body' : string,
  'sentAt' : bigint,
  'attachmentUrls' : Array<string>,
}
export interface SentMessageCreate {
  'leadIds' : Array<LeadId>,
  'subject' : string,
  'templateId' : [] | [TemplateId],
  'body' : string,
  'attachmentUrls' : Array<string>,
}
export type SentMessageId = bigint;
export type TemplateId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkImportLeads' : ActorMethod<[Array<LeadCreate>], Array<Lead>>,
  'createLead' : ActorMethod<[LeadCreate], Lead>,
  'createMessageTemplate' : ActorMethod<
    [MessageTemplateCreate],
    MessageTemplate
  >,
  'deleteLead' : ActorMethod<[LeadId], undefined>,
  'deleteMessageTemplate' : ActorMethod<[TemplateId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'closedLeads' : bigint,
      'newLeads' : bigint,
      'totalSentMessages' : bigint,
      'qualifiedLeads' : bigint,
      'totalTemplates' : bigint,
      'contactedLeads' : bigint,
    }
  >,
  'getLead' : ActorMethod<[LeadId], Lead>,
  'getMessageTemplate' : ActorMethod<[TemplateId], MessageTemplate>,
  'getSentMessage' : ActorMethod<[SentMessageId], SentMessage>,
  'getSentMessagesByLead' : ActorMethod<[LeadId], Array<SentMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'listMessageTemplates' : ActorMethod<[], Array<MessageTemplate>>,
  'listSentMessages' : ActorMethod<[], Array<SentMessage>>,
  'recordSentMessage' : ActorMethod<[SentMessageCreate], SentMessage>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLead' : ActorMethod<[LeadId, LeadCreate], Lead>,
  'updateMessageTemplate' : ActorMethod<
    [TemplateId, MessageTemplateCreate],
    MessageTemplate
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];