/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'contacted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const LeadCreate = IDL.Record({
  'status' : LeadStatus,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadId = IDL.Nat;
export const Lead = IDL.Record({
  'id' : LeadId,
  'status' : LeadStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const MessageTemplateCreate = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'attachmentUrls' : IDL.Vec(IDL.Text),
});
export const TemplateId = IDL.Nat;
export const MessageTemplate = IDL.Record({
  'id' : TemplateId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'attachmentUrls' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SentMessageId = IDL.Nat;
export const SentMessage = IDL.Record({
  'id' : SentMessageId,
  'leadIds' : IDL.Vec(LeadId),
  'subject' : IDL.Text,
  'templateId' : IDL.Opt(TemplateId),
  'body' : IDL.Text,
  'sentAt' : IDL.Int,
  'attachmentUrls' : IDL.Vec(IDL.Text),
});
export const SentMessageCreate = IDL.Record({
  'leadIds' : IDL.Vec(LeadId),
  'subject' : IDL.Text,
  'templateId' : IDL.Opt(TemplateId),
  'body' : IDL.Text,
  'attachmentUrls' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportLeads' : IDL.Func([IDL.Vec(LeadCreate)], [IDL.Vec(Lead)], []),
  'createLead' : IDL.Func([LeadCreate], [Lead], []),
  'createMessageTemplate' : IDL.Func(
      [MessageTemplateCreate],
      [MessageTemplate],
      [],
    ),
  'deleteLead' : IDL.Func([LeadId], [], []),
  'deleteMessageTemplate' : IDL.Func([TemplateId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'closedLeads' : IDL.Nat,
          'newLeads' : IDL.Nat,
          'totalSentMessages' : IDL.Nat,
          'qualifiedLeads' : IDL.Nat,
          'totalTemplates' : IDL.Nat,
          'contactedLeads' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLead' : IDL.Func([LeadId], [Lead], ['query']),
  'getMessageTemplate' : IDL.Func([TemplateId], [MessageTemplate], ['query']),
  'getSentMessage' : IDL.Func([SentMessageId], [SentMessage], ['query']),
  'getSentMessagesByLead' : IDL.Func(
      [LeadId],
      [IDL.Vec(SentMessage)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'listMessageTemplates' : IDL.Func([], [IDL.Vec(MessageTemplate)], ['query']),
  'listSentMessages' : IDL.Func([], [IDL.Vec(SentMessage)], ['query']),
  'recordSentMessage' : IDL.Func([SentMessageCreate], [SentMessage], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLead' : IDL.Func([LeadId, LeadCreate], [Lead], []),
  'updateMessageTemplate' : IDL.Func(
      [TemplateId, MessageTemplateCreate],
      [MessageTemplate],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'contacted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const LeadCreate = IDL.Record({
    'status' : LeadStatus,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadId = IDL.Nat;
  const Lead = IDL.Record({
    'id' : LeadId,
    'status' : LeadStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MessageTemplateCreate = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'attachmentUrls' : IDL.Vec(IDL.Text),
  });
  const TemplateId = IDL.Nat;
  const MessageTemplate = IDL.Record({
    'id' : TemplateId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'attachmentUrls' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SentMessageId = IDL.Nat;
  const SentMessage = IDL.Record({
    'id' : SentMessageId,
    'leadIds' : IDL.Vec(LeadId),
    'subject' : IDL.Text,
    'templateId' : IDL.Opt(TemplateId),
    'body' : IDL.Text,
    'sentAt' : IDL.Int,
    'attachmentUrls' : IDL.Vec(IDL.Text),
  });
  const SentMessageCreate = IDL.Record({
    'leadIds' : IDL.Vec(LeadId),
    'subject' : IDL.Text,
    'templateId' : IDL.Opt(TemplateId),
    'body' : IDL.Text,
    'attachmentUrls' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportLeads' : IDL.Func([IDL.Vec(LeadCreate)], [IDL.Vec(Lead)], []),
    'createLead' : IDL.Func([LeadCreate], [Lead], []),
    'createMessageTemplate' : IDL.Func(
        [MessageTemplateCreate],
        [MessageTemplate],
        [],
      ),
    'deleteLead' : IDL.Func([LeadId], [], []),
    'deleteMessageTemplate' : IDL.Func([TemplateId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'closedLeads' : IDL.Nat,
            'newLeads' : IDL.Nat,
            'totalSentMessages' : IDL.Nat,
            'qualifiedLeads' : IDL.Nat,
            'totalTemplates' : IDL.Nat,
            'contactedLeads' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLead' : IDL.Func([LeadId], [Lead], ['query']),
    'getMessageTemplate' : IDL.Func([TemplateId], [MessageTemplate], ['query']),
    'getSentMessage' : IDL.Func([SentMessageId], [SentMessage], ['query']),
    'getSentMessagesByLead' : IDL.Func(
        [LeadId],
        [IDL.Vec(SentMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'listMessageTemplates' : IDL.Func(
        [],
        [IDL.Vec(MessageTemplate)],
        ['query'],
      ),
    'listSentMessages' : IDL.Func([], [IDL.Vec(SentMessage)], ['query']),
    'recordSentMessage' : IDL.Func([SentMessageCreate], [SentMessage], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLead' : IDL.Func([LeadId, LeadCreate], [Lead], []),
    'updateMessageTemplate' : IDL.Func(
        [TemplateId, MessageTemplateCreate],
        [MessageTemplate],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };