/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type LeadId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type TemplateId = bigint;
export interface LeadCreate {
    status: LeadStatus;
    name: string;
    tags: Array<string>;
    email: string;
    notes: string;
    phone: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SentMessageCreate {
    leadIds: Array<LeadId>;
    subject: string;
    templateId?: TemplateId;
    body: string;
    attachmentUrls: Array<string>;
}
export interface Lead {
    id: LeadId;
    status: LeadStatus;
    name: string;
    createdAt: bigint;
    tags: Array<string>;
    email: string;
    notes: string;
    phone: string;
}
export interface MessageTemplate {
    id: TemplateId;
    title: string;
    body: string;
    createdAt: bigint;
    attachmentUrls: Array<string>;
}
export interface SentMessage {
    id: SentMessageId;
    leadIds: Array<LeadId>;
    subject: string;
    templateId?: TemplateId;
    body: string;
    sentAt: bigint;
    attachmentUrls: Array<string>;
}
export type SentMessageId = bigint;
export interface MessageTemplateCreate {
    title: string;
    body: string;
    attachmentUrls: Array<string>;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum LeadStatus {
    new_ = "new",
    closed = "closed",
    contacted = "contacted",
    qualified = "qualified"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportLeads(leadsCreate: Array<LeadCreate>): Promise<Array<Lead>>;
    createLead(leadCreate: LeadCreate): Promise<Lead>;
    createMessageTemplate(templateCreate: MessageTemplateCreate): Promise<MessageTemplate>;
    deleteLead(id: LeadId): Promise<void>;
    deleteMessageTemplate(id: TemplateId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        closedLeads: bigint;
        newLeads: bigint;
        totalSentMessages: bigint;
        qualifiedLeads: bigint;
        totalTemplates: bigint;
        contactedLeads: bigint;
    }>;
    getLead(id: LeadId): Promise<Lead>;
    getMessageTemplate(id: TemplateId): Promise<MessageTemplate>;
    getSentMessage(id: SentMessageId): Promise<SentMessage>;
    getSentMessagesByLead(leadId: LeadId): Promise<Array<SentMessage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listLeads(): Promise<Array<Lead>>;
    listMessageTemplates(): Promise<Array<MessageTemplate>>;
    listSentMessages(): Promise<Array<SentMessage>>;
    recordSentMessage(messageCreate: SentMessageCreate): Promise<SentMessage>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateLead(id: LeadId, leadUpdate: LeadCreate): Promise<Lead>;
    updateMessageTemplate(id: TemplateId, templateUpdate: MessageTemplateCreate): Promise<MessageTemplate>;
}
import type { Lead as _Lead, LeadCreate as _LeadCreate, LeadId as _LeadId, LeadStatus as _LeadStatus, SentMessage as _SentMessage, SentMessageCreate as _SentMessageCreate, SentMessageId as _SentMessageId, TemplateId as _TemplateId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkImportLeads(arg0: Array<LeadCreate>): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportLeads(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportLeads(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLead(arg0: LeadCreate): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_LeadCreate_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Lead_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_LeadCreate_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Lead_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMessageTemplate(arg0: MessageTemplateCreate): Promise<MessageTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createMessageTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMessageTemplate(arg0);
            return result;
        }
    }
    async deleteLead(arg0: LeadId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteMessageTemplate(arg0: TemplateId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessageTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessageTemplate(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        closedLeads: bigint;
        newLeads: bigint;
        totalSentMessages: bigint;
        qualifiedLeads: bigint;
        totalTemplates: bigint;
        contactedLeads: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLead(arg0: LeadId): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_Lead_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_Lead_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageTemplate(arg0: TemplateId): Promise<MessageTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageTemplate(arg0);
            return result;
        }
    }
    async getSentMessage(arg0: SentMessageId): Promise<SentMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentMessage(arg0);
                return from_candid_SentMessage_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentMessage(arg0);
            return from_candid_SentMessage_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSentMessagesByLead(arg0: LeadId): Promise<Array<SentMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentMessagesByLead(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentMessagesByLead(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMessageTemplates(): Promise<Array<MessageTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessageTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessageTemplates();
            return result;
        }
    }
    async listSentMessages(): Promise<Array<SentMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSentMessages();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSentMessages();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordSentMessage(arg0: SentMessageCreate): Promise<SentMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSentMessage(to_candid_SentMessageCreate_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SentMessage_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSentMessage(to_candid_SentMessageCreate_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SentMessage_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateLead(arg0: LeadId, arg1: LeadCreate): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_LeadCreate_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Lead_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_LeadCreate_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Lead_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMessageTemplate(arg0: TemplateId, arg1: MessageTemplateCreate): Promise<MessageTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMessageTemplate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMessageTemplate(arg0, arg1);
            return result;
        }
    }
}
function from_candid_LeadStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SentMessage_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SentMessage): SentMessage {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TemplateId]): TemplateId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LeadId;
    status: _LeadStatus;
    name: string;
    createdAt: bigint;
    tags: Array<string>;
    email: string;
    notes: string;
    phone: string;
}): {
    id: LeadId;
    status: LeadStatus;
    name: string;
    createdAt: bigint;
    tags: Array<string>;
    email: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n18(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        email: value.email,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SentMessageId;
    leadIds: Array<_LeadId>;
    subject: string;
    templateId: [] | [_TemplateId];
    body: string;
    sentAt: bigint;
    attachmentUrls: Array<string>;
}): {
    id: SentMessageId;
    leadIds: Array<LeadId>;
    subject: string;
    templateId?: TemplateId;
    body: string;
    sentAt: bigint;
    attachmentUrls: Array<string>;
} {
    return {
        id: value.id,
        leadIds: value.leadIds,
        subject: value.subject,
        templateId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.templateId)),
        body: value.body,
        sentAt: value.sentAt,
        attachmentUrls: value.attachmentUrls
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closed: null;
} | {
    contacted: null;
} | {
    qualified: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new_ : "closed" in value ? LeadStatus.closed : "contacted" in value ? LeadStatus.contacted : "qualified" in value ? LeadStatus.qualified : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SentMessage>): Array<SentMessage> {
    return value.map((x)=>from_candid_SentMessage_n23(_uploadFile, _downloadFile, x));
}
function to_candid_LeadCreate_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadCreate): _LeadCreate {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SentMessageCreate_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SentMessageCreate): _SentMessageCreate {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: LeadStatus;
    name: string;
    tags: Array<string>;
    email: string;
    notes: string;
    phone: string;
}): {
    status: _LeadStatus;
    name: string;
    tags: Array<string>;
    email: string;
    notes: string;
    phone: string;
} {
    return {
        status: to_candid_LeadStatus_n13(_uploadFile, _downloadFile, value.status),
        name: value.name,
        tags: value.tags,
        email: value.email,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadIds: Array<LeadId>;
    subject: string;
    templateId?: TemplateId;
    body: string;
    attachmentUrls: Array<string>;
}): {
    leadIds: Array<_LeadId>;
    subject: string;
    templateId: [] | [_TemplateId];
    body: string;
    attachmentUrls: Array<string>;
} {
    return {
        leadIds: value.leadIds,
        subject: value.subject,
        templateId: value.templateId ? candid_some(value.templateId) : candid_none(),
        body: value.body,
        attachmentUrls: value.attachmentUrls
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    new: null;
} | {
    closed: null;
} | {
    contacted: null;
} | {
    qualified: null;
} {
    return value == LeadStatus.new_ ? {
        new: null
    } : value == LeadStatus.closed ? {
        closed: null
    } : value == LeadStatus.contacted ? {
        contacted: null
    } : value == LeadStatus.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LeadCreate>): Array<_LeadCreate> {
    return value.map((x)=>to_candid_LeadCreate_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
